# Dependabot template

version: 2
updates:

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "git submod"
    labels:
      - "git submods"
      - "updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "git action"
    labels:
      - "git actions"
      - "updates"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"